name: check-dependency-versions

on:
  schedule:
    - cron: '30 1 1,15 * *'

jobs:
  check-dependencies:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Finding dependency updates
        run:  mvn versions:display-dependency-updates -Dversions.outputFile=report.txt
      - name: Update dependencies to latest version
        run: mvn versions:use-latest-releases -DgenerateBackupPoms=true
      - name: Checking if there was any updated dependency
        id: update-check
        run: (test -f pom.xml.versionsBackup  && echo "::set-output name=updated::true") || echo "No version was updated"
      - name: Execute tests
        id: test-execution
        run: (mvn clean test && echo "::set-output name=result::\"Dependencies can be updated\"") || (echo "::set-output name=failed::true" && echo "::set-output name=result::\"Can not update dependencies\"")
        if: ${{ steps.update-check.updated }}
      - name: Create Issue From File
        if: ${{ steps.update-check.updated }}
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: ${{ steps.test-execution.outputs.result }}
          content-filepath: ./report.txt
          labels: dependencies, automation
